import { build } from 'esbuild';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const output = resolve(root, 'src/verifier/verifierBundle.generated.ts');
async function main(): Promise<void> {
  const result = await build({
    entryPoints: [resolve(root, 'src/verifier/browser-entry.ts')],
    bundle: true,
    write: false,
    format: 'iife',
    platform: 'browser',
    target: ['safari17'],
    minify: true,
    legalComments: 'none',
    sourcemap: false,
    charset: 'utf8',
    define: {
      'process.env.NODE_ENV': '"production"',
    },
  });
  const script = result.outputFiles[0]?.text;
  if (!script)
    throw new Error('Verifier bundling produced no JavaScript output.');
  const html = `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; connect-src 'none'; img-src 'none'; style-src 'none'; frame-src 'none'; base-uri 'none'; form-action 'none'"></head><body><script>${script.replaceAll(
    '</script',
    '<\\/script',
  )}</script></body></html>`;
  await mkdir(dirname(output), { recursive: true });
  await writeFile(
    output,
    `// Generated by scripts/build-verifier.ts. Do not edit.\nexport const verifierHtml = ${JSON.stringify(
      html,
    )};\n`,
    'utf8',
  );
}

void main();
